Ruslan
k4rtsen/AstonTask pull request #15
Opened 2024-12-24 08:39 UTC by nalsur-job

2024-12-24 10:21 UTC, merged

2024-12-24 10:26 UTC, MeganDorian requested changes
@k4rtsen накидала замечаний по рефакторингу и есть несколько вопросов по поводу логики

2024-12-24 10:26 UTC, MeganDorian commented on MainTask/src/ruslan/ClownUtilities.java
>          return (char) getRandomNumber(65,70)+
тут тоже магические числа

2024-12-24 10:26 UTC, MeganDorian commented on MainTask/src/ruslan/ClownUtilities.java
> +        return Double.parseDouble(String.valueOf(((Math.random() * (max - min)) + min)).substring(0,3));
а зачем?

2024-12-24 10:26 UTC, MeganDorian commented on MainTask/src/ruslan/ClownUtilities.java
>       */
не могу сделать коммент к не измененным строкам:
63-66ч строки: так ты нормально на пароль не проверишь
https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a выбери что-то из этого, к примеру

особенно на 64 строке: regex выглядит как "любой символ 0 или бесконечно раз, затем одим символ из symbolsSpec и затем любом символ 0 или бесконечно много раз"

regexы тоже лучше выносить куда-нибудь отдельно и давать им осознанные имена, ибо сходу сейчас и не скажешь что у тебя в этих строках каждая регулярка что именно проверяет

2024-12-24 10:26 UTC, MeganDorian commented on MainTask/src/ruslan/ClownUtilities.java
>          return (char) getRandomNumber(65,70)+
даже если бы ты написал что-то вроде  `getRandomNumber((int) 'a', (int) 'z')` было бы понятнее

2024-12-24 10:38 UTC, nalsur-job commented on MainTask/src/MainUI.java
>      static void classMenu(String className) throws IOException {
> ... тут classMenu поменяй на modelsMenu ..
ок

2024-12-24 10:39 UTC, nalsur-job commented on MainTask/src/MainUI.java
> -    static void fromFile(String className) throws IOException {
ок

2024-12-24 10:39 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +                    quickSortBus(buses);
на тот момент, когда делал - было актуально ... поправлю.

2024-12-24 10:40 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +                    System.out.println("\nАвтобусы в массиве сортировки:");
очепятка, поправлю

2024-12-24 10:40 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +        try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(filePath, true))) {
принято, займусь

2024-12-24 10:43 UTC, nalsur-job commented on MainTask/src/ruslan/ClownUtilities.java
> +        return Double.parseDouble(String.valueOf(((Math.random() * (max - min)) + min)).substring(0,3));
что именно зачем? из doluble через string, через через? Задумка была чтобы метод передавал 2 знака после запятой ... без этих манипуляций он передает double с большим кол-м знаков .. что не нужно.
Или есть другой способ?

2024-12-24 10:54 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +                    for (Student it : students) {
надо обсуждать. В доп. доп. не сказано про спрашивать ... а вывод, точнее дозапись в файл (один файл) результата сортировки и поска

2024-12-24 10:58 UTC, MeganDorian commented on MainTask/src/ruslan/ClownUtilities.java
> +        return Double.parseDouble(String.valueOf(((Math.random() * (max - min)) + min)).substring(0,3));
можно сделать так:  
```
double number = (double) ((Math.random() * (max - min)) + min);
return Math.round(number * 100) / 100;
```

2024-12-24 11:00 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +                case "3":
1) Вывести массив в консоль
2) Отсортировать массив быстрой сортировкой
3) Отсортировать массив по определенному полю
4) Найти элемент (бинарный поиск)
5) Вернуться в предыдущее меню

2024-12-24 12:57 UTC, nalsur-job commented on MainTask/src/ruslan/ClownUtilities.java
> +        return Double.parseDouble(String.valueOf(((Math.random() * (max - min)) + min)).substring(0,3));
спасибо, сделаю так

2024-12-24 19:42 UTC, nalsur-job commented on MainTask/src/MainUI.java
>      static void classMenu(String className) throws IOException {
сделано

2024-12-24 19:43 UTC, nalsur-job commented on MainTask/src/MainUI.java
> -    static void fromFile(String className) throws IOException {
сделано, вынесено в отдельный пакет filling в класс ByFromFile

2024-12-24 19:43 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +                    quickSortBus(buses);
исправлено

2024-12-24 19:43 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +                    System.out.println("\nАвтобусы в массиве сортировки:");
Откорректировано

2024-12-24 19:44 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +        try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(filePath, true))) {
поправил, пока до дженериков не дошел - завтра

2024-12-24 19:44 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +                    .setPassword(getRandomUserSecret(8))
Сделаны константы, убраны магические числа

2024-12-24 19:44 UTC, nalsur-job commented on MainTask/src/MainUI.java
> -import java.io.BufferedReader;
рассортированы классы по пакетам

2024-12-24 19:44 UTC, nalsur-job commented on MainTask/src/ruslan/ClownUtilities.java
> +        return Double.parseDouble(String.valueOf(((Math.random() * (max - min)) + min)).substring(0,3));
готово

2024-12-24 19:45 UTC, nalsur-job commented on MainTask/src/MainUI.java
> +    static void fillByManual(String className) throws IOException {
переработано, стало красивее

2024-12-25 05:44 UTC, nalsur-job commented on MainTask/src/ruslan/ClownUtilities.java
>          return (char) getRandomNumber(65,70)+
откорректировано

2024-12-25 05:46 UTC, nalsur-job commented on MainTask/src/ruslan/ClownUtilities.java
>       */
тут не проверка на пароль т.е. **это не валидация!**, а **генерация** пароля **с заданной сложностью** ... чтобы обязательно были в пароле заглавная буква, прописная буква, цифра и спец символ.
валидация как раз на тебе :-)